class EventType:
    # Только для пользователя
    INTERACTION_CREATE = -9  # создание слэш-команды
    INTERACTION_SUCCESS = -8  # успешная слэш-команда
    RELATIONSHIP_ADD = -7  # добавление в друзья
    RELATIONSHIP_REMOVE = -6  # удаление из друзей
    MESSAGE_REACTION_REMOVE = -5
    MESSAGE_REACTION_ADD = -4
    PRESENCE_UPDATE = -3
    READY_SUPPLEMENTAL = -2
    # READY = -1

    # Общие (Пользователи + Боты)
    GUILD_UPDATE = 1
    CHANNEL_CREATE = 10
    CHANNEL_UPDATE = 11
    CHANNEL_DELETE = 12
    CHANNEL_OVERWRITE_CREATE = 13
    CHANNEL_OVERWRITE_UPDATE = 14
    CHANNEL_OVERWRITE_DELETE = 15
    MEMBER_KICK = 20
    MEMBER_PRUNE = 21
    MEMBER_BAN_ADD = 22
    MEMBER_BAN_REMOVE = 23
    MEMBER_UPDATE = 24
    MEMBER_ROLE_UPDATE = 25
    MEMBER_MOVE = 26
    MEMBER_DISCONNECT = 27
    BOT_ADD = 28
    ROLE_CREATE = 30
    ROLE_UPDATE = 31
    ROLE_DELETE = 32
    INVITE_CREATE = 40
    INVITE_UPDATE = 41
    INVITE_DELETE = 42
    WEBHOOK_CREATE = 50
    WEBHOOK_UPDATE = 51
    WEBHOOK_DELETE = 52
    EMOJI_CREATE = 60
    EMOJI_UPDATE = 61
    EMOJI_DELETE = 62
    MESSAGE_DELETE = 72
    MESSAGE_BULK_DELETE = 73
    MESSAGE_PIN = 74
    MESSAGE_UNPIN = 75
    INTEGRATION_CREATE = 80
    INTEGRATION_UPDATE = 81
    INTEGRATION_DELETE = 82
    STAGE_INSTANCE_CREATE = 83
    STAGE_INSTANCE_UPDATE = 84
    STAGE_INSTANCE_DELETE = 85
    STICKER_CREATE = 90
    STICKER_UPDATE = 91
    STICKER_DELETE = 92
    GUILD_SCHEDULED_EVENT_CREATE = 100
    GUILD_SCHEDULED_EVENT_UPDATE = 101
    GUILD_SCHEDULED_EVENT_DELETE = 102
    THREAD_CREATE = 110
    THREAD_UPDATE = 111
    THREAD_DELETE = 112
    APPLICATION_COMMAND_PERMISSION_UPDATE = 121
    SOUNDBOARD_SOUND_CREATE = 130
    SOUNDBOARD_SOUND_UPDATE = 131
    SOUNDBOARD_SOUND_DELETE = 132
    AUTO_MODERATION_RULE_CREATE = 140
    AUTO_MODERATION_RULE_UPDATE = 141
    AUTO_MODERATION_RULE_DELETE = 142
    AUTO_MODERATION_BLOCK_MESSAGE = 143
    AUTO_MODERATION_FLAG_TO_CHANNEL = 144
    AUTO_MODERATION_USER_COMMUNICATION_DISABLED = 145
    AUTO_MODERATION_QUARANTINE_USER = 146
    CREATOR_MONETIZATION_REQUEST_CREATED = 150
    CREATOR_MONETIZATION_TERMS_ACCEPTED = 151
    ONBOARDING_PROMPT_CREATE = 163
    ONBOARDING_PROMPT_UPDATE = 164
    ONBOARDING_PROMPT_DELETE = 165
    ONBOARDING_CREATE = 166
    ONBOARDING_UPDATE = 167
    GUILD_HOME_FEATURE_ITEM = 171
    GUILD_HOME_REMOVE_ITEM = 172
    HARMFUL_LINKS_BLOCKED_MESSAGE = 180
    HOME_SETTINGS_CREATE = 190
    HOME_SETTINGS_UPDATE = 191
    VOICE_CHANNEL_STATUS_CREATE = 192
    VOICE_CHANNEL_STATUS_DELETE = 193
    CLYDE_AI_PROFILE_UPDATE = 194
    GUILD_SCHEDULED_EVENT_EXCEPTION_CREATE = 200
    GUILD_SCHEDULED_EVENT_EXCEPTION_UPDATE = 201
    GUILD_SCHEDULED_EVENT_EXCEPTION_DELETE = 202


def get_event_code(event_name):
    event_mapping = {
        'INTERACTION_CREATE': EventType.INTERACTION_CREATE,
        'INTERACTION_SUCCESS': EventType.INTERACTION_SUCCESS,
        'RELATIONSHIP_ADD': EventType.RELATIONSHIP_ADD,  # type 3 - входящие, 4 - отправленные, 1 - принятый
        'RELATIONSHIP_REMOVE': EventType.RELATIONSHIP_REMOVE,
        'MESSAGE_REACTION_REMOVE': EventType.MESSAGE_REACTION_REMOVE,
        'MESSAGE_REACTION_ADD': EventType.MESSAGE_REACTION_ADD,
        'PRESENCE_UPDATE': EventType.PRESENCE_UPDATE,
        'READY_SUPPLEMENTAL': EventType.READY_SUPPLEMENTAL,

        'GUILD_UPDATE': EventType.GUILD_UPDATE,
        'CHANNEL_CREATE': EventType.CHANNEL_CREATE,
        'CHANNEL_UPDATE': EventType.CHANNEL_UPDATE,
        'CHANNEL_DELETE': EventType.CHANNEL_DELETE,
        'CHANNEL_OVERWRITE_CREATE': EventType.CHANNEL_OVERWRITE_CREATE,
        'CHANNEL_OVERWRITE_UPDATE': EventType.CHANNEL_OVERWRITE_UPDATE,
        'CHANNEL_OVERWRITE_DELETE': EventType.CHANNEL_OVERWRITE_DELETE,
        'MEMBER_KICK': EventType.MEMBER_KICK,
        'MEMBER_PRUNE': EventType.MEMBER_PRUNE,
        'MEMBER_BAN_ADD': EventType.MEMBER_BAN_ADD,
        'MEMBER_BAN_REMOVE': EventType.MEMBER_BAN_REMOVE,
        'MEMBER_UPDATE': EventType.MEMBER_UPDATE,
        'MEMBER_ROLE_UPDATE': EventType.MEMBER_ROLE_UPDATE,
        'MEMBER_MOVE': EventType.MEMBER_MOVE,
        'MEMBER_DISCONNECT': EventType.MEMBER_DISCONNECT,
        'BOT_ADD': EventType.BOT_ADD,
        'ROLE_CREATE': EventType.ROLE_CREATE,
        'ROLE_UPDATE': EventType.ROLE_UPDATE,
        'ROLE_DELETE': EventType.ROLE_DELETE,
        'INVITE_CREATE': EventType.INVITE_CREATE,
        'INVITE_UPDATE': EventType.INVITE_UPDATE,
        'INVITE_DELETE': EventType.INVITE_DELETE,
        'WEBHOOK_CREATE': EventType.WEBHOOK_CREATE,
        'WEBHOOK_UPDATE': EventType.WEBHOOK_UPDATE,
        'WEBHOOK_DELETE': EventType.WEBHOOK_DELETE,
        'EMOJI_CREATE': EventType.EMOJI_CREATE,
        'EMOJI_UPDATE': EventType.EMOJI_UPDATE,
        'EMOJI_DELETE': EventType.EMOJI_DELETE,
        'MESSAGE_DELETE': EventType.MESSAGE_DELETE,
        'MESSAGE_BULK_DELETE': EventType.MESSAGE_BULK_DELETE,
        'MESSAGE_PIN': EventType.MESSAGE_PIN,
        'MESSAGE_UNPIN': EventType.MESSAGE_UNPIN,
        'INTEGRATION_CREATE': EventType.INTEGRATION_CREATE,
        'INTEGRATION_UPDATE': EventType.INTEGRATION_UPDATE,
        'INTEGRATION_DELETE': EventType.INTEGRATION_DELETE,
        'STAGE_INSTANCE_CREATE': EventType.STAGE_INSTANCE_CREATE,
        'STAGE_INSTANCE_UPDATE': EventType.STAGE_INSTANCE_UPDATE,
        'STAGE_INSTANCE_DELETE': EventType.STAGE_INSTANCE_DELETE,
        'STICKER_CREATE': EventType.STICKER_CREATE,
        'STICKER_UPDATE': EventType.STICKER_UPDATE,
        'STICKER_DELETE': EventType.STICKER_DELETE,
        'GUILD_SCHEDULED_EVENT_CREATE': EventType.GUILD_SCHEDULED_EVENT_CREATE,
        'GUILD_SCHEDULED_EVENT_UPDATE': EventType.GUILD_SCHEDULED_EVENT_UPDATE,
        'GUILD_SCHEDULED_EVENT_DELETE': EventType.GUILD_SCHEDULED_EVENT_DELETE,
        'THREAD_CREATE': EventType.THREAD_CREATE,
        'THREAD_UPDATE': EventType.THREAD_UPDATE,
        'THREAD_DELETE': EventType.THREAD_DELETE,
        'APPLICATION_COMMAND_PERMISSION_UPDATE': EventType.APPLICATION_COMMAND_PERMISSION_UPDATE,
        'SOUNDBOARD_SOUND_CREATE': EventType.SOUNDBOARD_SOUND_CREATE,
        'SOUNDBOARD_SOUND_UPDATE': EventType.SOUNDBOARD_SOUND_UPDATE,
        'SOUNDBOARD_SOUND_DELETE': EventType.SOUNDBOARD_SOUND_DELETE,
        'AUTO_MODERATION_RULE_CREATE': EventType.AUTO_MODERATION_RULE_CREATE,
        'AUTO_MODERATION_RULE_UPDATE': EventType.AUTO_MODERATION_RULE_UPDATE,
        'AUTO_MODERATION_RULE_DELETE': EventType.AUTO_MODERATION_RULE_DELETE,
        'AUTO_MODERATION_BLOCK_MESSAGE': EventType.AUTO_MODERATION_BLOCK_MESSAGE,
        'AUTO_MODERATION_FLAG_TO_CHANNEL': EventType.AUTO_MODERATION_FLAG_TO_CHANNEL,
        'AUTO_MODERATION_USER_COMMUNICATION_DISABLED': EventType.AUTO_MODERATION_USER_COMMUNICATION_DISABLED,
        'AUTO_MODERATION_QUARANTINE_USER': EventType.AUTO_MODERATION_QUARANTINE_USER,
        'CREATOR_MONETIZATION_REQUEST_CREATED': EventType.CREATOR_MONETIZATION_REQUEST_CREATED,
        'CREATOR_MONETIZATION_TERMS_ACCEPTED': EventType.CREATOR_MONETIZATION_TERMS_ACCEPTED,
        'ONBOARDING_PROMPT_CREATE': EventType.ONBOARDING_PROMPT_CREATE,
        'ONBOARDING_PROMPT_UPDATE': EventType.ONBOARDING_PROMPT_UPDATE,
        'ONBOARDING_PROMPT_DELETE': EventType.ONBOARDING_PROMPT_DELETE,
        'ONBOARDING_CREATE': EventType.ONBOARDING_CREATE,
        'ONBOARDING_UPDATE': EventType.ONBOARDING_UPDATE,
        'GUILD_HOME_FEATURE_ITEM': EventType.GUILD_HOME_FEATURE_ITEM,
        'GUILD_HOME_REMOVE_ITEM': EventType.GUILD_HOME_REMOVE_ITEM,
        'HARMFUL_LINKS_BLOCKED_MESSAGE': EventType.HARMFUL_LINKS_BLOCKED_MESSAGE,
        'HOME_SETTINGS_CREATE': EventType.HOME_SETTINGS_CREATE,
        'HOME_SETTINGS_UPDATE': EventType.HOME_SETTINGS_UPDATE,
        'VOICE_CHANNEL_STATUS_CREATE': EventType.VOICE_CHANNEL_STATUS_CREATE,
        'VOICE_CHANNEL_STATUS_DELETE': EventType.VOICE_CHANNEL_STATUS_DELETE,
        'CLYDE_AI_PROFILE_UPDATE': EventType.CLYDE_AI_PROFILE_UPDATE,
        'GUILD_SCHEDULED_EVENT_EXCEPTION_CREATE': EventType.GUILD_SCHEDULED_EVENT_EXCEPTION_CREATE,
        'GUILD_SCHEDULED_EVENT_EXCEPTION_UPDATE': EventType.GUILD_SCHEDULED_EVENT_EXCEPTION_UPDATE,
        'GUILD_SCHEDULED_EVENT_EXCEPTION_DELETE': EventType.GUILD_SCHEDULED_EVENT_EXCEPTION_DELETE,
    }
    return event_mapping.get(event_name)
